# Generated by Django 5.2.4 on 2025-07-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_contact_galleryimage_delete_contactmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
