# Generated by Django 5.2.4 on 2025-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_enquiry_delete_brochurerequest_delete_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
